package com.petjar.entities;
// Generated Feb 7, 2014 1:23:49 PM by Hibernate Tools 3.6.0



/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private Integer contentId;
     private int articleId;
     private int languageId;
     private String content;

    public Article() {
    }

	
    public Article(int articleId, int languageId) {
        this.articleId = articleId;
        this.languageId = languageId;
    }
    public Article(int articleId, int languageId, String content) {
       this.articleId = articleId;
       this.languageId = languageId;
       this.content = content;
    }
   
    public Integer getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }
    public int getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(int articleId) {
        this.articleId = articleId;
    }
    public int getLanguageId() {
        return this.languageId;
    }
    
    public void setLanguageId(int languageId) {
        this.languageId = languageId;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


