package com.petjar.entities;
// Generated Feb 7, 2014 1:23:49 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Binaryinfo generated by hbm2java
 */
public class Binaryinfo  implements java.io.Serializable {


     private Integer binaryId;
     private Date createDate;
     private Date modifiedDate;
     private byte[] metadata;
     private String uri;

    public Binaryinfo() {
    }

	
    public Binaryinfo(Date createDate, Date modifiedDate, byte[] metadata) {
        this.createDate = createDate;
        this.modifiedDate = modifiedDate;
        this.metadata = metadata;
    }
    public Binaryinfo(Date createDate, Date modifiedDate, byte[] metadata, String uri) {
       this.createDate = createDate;
       this.modifiedDate = modifiedDate;
       this.metadata = metadata;
       this.uri = uri;
    }
   
    public Integer getBinaryId() {
        return this.binaryId;
    }
    
    public void setBinaryId(Integer binaryId) {
        this.binaryId = binaryId;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public byte[] getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(byte[] metadata) {
        this.metadata = metadata;
    }
    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }




}


